# Generated by Django 3.2.9 on 2022-03-10 05:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ckeditor_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=40, null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Thumb', models.ImageField(null=True, upload_to='static/img')),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Duration', models.CharField(choices=[('1 mon', '1 MONTH'), ('6 mon', '6 MONTH'), ('3 mon', '3 MONTH')], max_length=100, null=True)),
                ('title', models.CharField(max_length=127)),
                ('sub_title', models.CharField(max_length=127)),
                ('is_official', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='courses_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(null=True, upload_to='static/course_img')),
                ('course_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('course_no', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=50, null=True)),
                ('slider_img', models.ImageField(null=True, upload_to='static/slider')),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
