# Generated by Django 3.2.9 on 2022-03-10 05:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=127, null=True)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('file', models.FileField(null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_num', models.PositiveSmallIntegerField(null=True)),
                ('week_num', models.PositiveSmallIntegerField(null=True)),
                ('title', models.CharField(default='', max_length=63, null=True)),
                ('description', ckeditor.fields.RichTextField(default='', null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('vimeo_url', models.URLField(blank=True, null=True)),
                ('bliptv_url', models.URLField(blank=True, null=True)),
                ('preferred_service', models.CharField(choices=[('1', 'YouTube'), ('2', 'Vimeo')], default='1', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.course')),
            ],
        ),
    ]
