# Generated by Django 3.2.9 on 2022-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20220310_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Thumb',
        ),
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.CharField(choices=[('6 mon', '6 MONTH'), ('3 mon', '3 MONTH'), ('1 mon', '1 MONTH')], max_length=100, null=True),
        ),
    ]
