# Generated by Django 3.2.9 on 2022-03-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.CharField(choices=[('6 mon', '6 MONTH'), ('3 mon', '3 MONTH'), ('1 mon', '1 MONTH')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
