# Generated by Django 3.2.9 on 2022-03-10 05:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100, null=True)),
                ('form_email', models.CharField(max_length=100, null=True)),
                ('form_subject', models.CharField(max_length=100, null=True)),
                ('form_message', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=50, null=True)),
                ('slider_img', models.ImageField(null=True, upload_to='static/slider')),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
