# Generated by Django 3.2.9 on 2022-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_email_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificateinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('Father_Name', models.CharField(max_length=50, null=True)),
                ('Admission_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
