# Generated by Django 4.1.4 on 2023-01-17 06:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_q_form_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300, null=True)),
                ('blog_img', models.ImageField(blank=True, upload_to='static/docs/')),
                ('blog_desp', ckeditor.fields.RichTextField()),
                ('blog_date', models.DateTimeField()),
            ],
        ),
    ]
