# Generated by Django 4.1.4 on 2023-01-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_blog_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_author',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
