# Generated by Django 4.1.4 on 2023-02-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_blog_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificateinfo',
        ),
    ]
