# Generated by Django 4.1.4 on 2023-03-01 06:28

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_delete_certificateinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(upload_to='media')),
                ('course_price', models.CharField(max_length=6, null=True)),
                ('course_title', models.CharField(max_length=30, null=True)),
                ('course_descp', ckeditor.fields.RichTextField()),
                ('course_stu', models.CharField(max_length=5, null=True)),
                ('course_lessons', models.CharField(max_length=4, null=True)),
                ('course_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_title', unique=True)),
            ],
        ),
    ]
