# Generated by Django 4.1.4 on 2023-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_blog_blog_slug_alter_blog_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_bann',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
