# Generated by Django 4.1.4 on 2023-03-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_course_course_bann'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=40, null=True)),
                ('stu_descp', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(),
        ),
    ]
