# Generated by Django 4.1.4 on 2023-03-02 08:32

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_stureview_alter_blog_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200, null=True)),
                ('event_img', models.ImageField(upload_to='media')),
                ('event_descp', ckeditor.fields.RichTextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=30, null=True)),
                ('event_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='event_title', unique=True)),
            ],
        ),
    ]
