# Generated by Django 3.2.9 on 2022-03-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_order_student_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='City',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Pincode',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='State',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
