# Generated by Django 3.2.9 on 2022-03-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20220313_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=4, null=True),
        ),
    ]
