# Generated by Django 3.2.9 on 2022-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20220313_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='Admission_no',
            field=models.CharField(default='4BRD/3BRD/8BRD/8BRD/2BRD/9', max_length=10),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Block',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='District',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='House',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student_detail',
            name='Post_office',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
    ]
