# Generated by Django 3.2.9 on 2022-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_alter_student_detail_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Admission_no',
            field=models.CharField(default='BRD/871809', max_length=10),
        ),
    ]
