# Generated by Django 3.2.9 on 2022-03-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_auto_20220321_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Admission_no',
            field=models.CharField(default='BRD/806113', max_length=10),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='doc_10',
            field=models.FileField(blank=True, null=True, upload_to='static/docs/'),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='doc_12',
            field=models.FileField(blank=True, null=True, upload_to='static/docs/'),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='doc_pg',
            field=models.FileField(blank=True, null=True, upload_to='static/docs/'),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='doc_ug',
            field=models.FileField(blank=True, null=True, upload_to='static/docs/'),
        ),
    ]
