# Generated by Django 3.2.9 on 2022-10-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0022_alter_student_detail_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Admission_no',
            field=models.CharField(default='AVI/557053', max_length=10),
        ),
    ]
