# Generated by Django 3.2.9 on 2022-11-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0025_alter_student_detail_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Admission_no',
            field=models.CharField(default='AIR/368582', max_length=10),
        ),
    ]
