# Generated by Django 3.2.9 on 2022-11-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_alter_student_detail_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Admission_no',
            field=models.CharField(default='AIR/811245', max_length=10),
        ),
    ]
